{{- if .Values.secretsStore.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretsStore.secretProviderClass.name }}
  namespace: {{ .Release.Namespace }}
spec:
  provider: {{ .Values.secretsStore.secretProviderClass.provider }}
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    keyvaultName: {{ .Values.secretsStore.secretProviderClass.azure.keyvaultName | quote }}
    tenantId: {{ .Values.secretsStore.secretProviderClass.azure.tenantId | quote }}
    objects: |
      array:
{{- range .Values.secretsStore.secretProviderClass.objects }}
        - |
          objectName: {{ .objectName }}
          objectType: {{ .objectType }}
{{- end }}
{{- end }}